version: '3.8'

services:
  web:
    container_name: postman_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - production

networks:
  production:
    external: true
    name: production
    driver: bridge
